// ──────────────────────────────────────────────────────────────────────────────
//  _DoNotTouch.swift
//  MLX-chatbot
//
//  ✋ DO NOT EDIT THIS FILE.
//
//  This file contains the app's structural wiring:
//    • Color(hex:) helper used by AppColors.swift
//    • The main ContentView layout (logo, nav bar, scroll view, reset dialog)
//    • The input bar (text field + send button)
//    • The model-loading overlay with progress bar
//
//  Changing anything here can break the app. All visual customisation lives in:
//    → AppConfig.swift   (text & questions)
//    → AppColors.swift   (colours)
//    → WelcomeView.swift (welcome screen layout)
//    → MessageBubble.swift (chat bubble style)
// ──────────────────────────────────────────────────────────────────────────────

import SwiftUI

// MARK: - Hex colour helper (used by AppColors.swift)

extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 3: (a, r, g, b) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default: (a, r, g, b) = (255, 0, 0, 0)
        }
        self.init(.sRGB, red: Double(r)/255, green: Double(g)/255,
                  blue: Double(b)/255, opacity: Double(a)/255)
    }
}

// MARK: - Content View

struct ContentView: View {
    @StateObject private var vm = ChatViewModel()
    @State private var showResetConfirm = false

    var body: some View {
        NavigationStack { homeView }
            .confirmationDialog("Reset Model?", isPresented: $showResetConfirm, titleVisibility: .visible) {
                Button("Delete Model & Adapters", role: .destructive) { vm.reset() }
                Button("Cancel", role: .cancel) {}
            } message: {
                Text("This deletes the trained model and adapters. You will need to run train_qwen_lora.py again before using the app.")
            }
    }

    private var homeView: some View {
        VStack(spacing: 0) {
            Image("Logo")
                .resizable()
                .aspectRatio(contentMode: .fit)
                .frame(width: 84, height: 84)
                .shadow(radius: 8)
                .padding(.top, 24)

            if vm.messages.isEmpty {
                WelcomeView { question in
                    vm.input = question
                    vm.send()
                }
            } else {
                messagesView
            }
            inputView
        }
        .navigationTitle(AppConfig.navigationTitle)
        .toolbar {
            ToolbarItem(placement: .automatic) {
                Button(role: .destructive) { showResetConfirm = true } label: {
                    Label("Reset Model", systemImage: "arrow.counterclockwise")
                }
                .disabled(vm.isModelLoading)
            }
        }
        .overlay(modelLoadingOverlay)
    }

    private var messagesView: some View {
        ScrollViewReader { proxy in
            ScrollView {
                LazyVStack(spacing: 12) {
                    ForEach(Array(vm.messages.enumerated()), id: \.offset) { index, message in
                        MessageBubble(message: message).id(index)
                    }
                }
                .padding()
            }
            .onChange(of: vm.messages.count) { _, _ in
                if let lastIndex = vm.messages.indices.last {
                    withAnimation(.easeInOut(duration: 0.5)) { proxy.scrollTo(lastIndex, anchor: .bottom) }
                }
            }
        }
    }

    private var inputView: some View {
        VStack(spacing: 0) {
            Divider()
            HStack(alignment: .top, spacing: 16) {
                TextField(AppConfig.inputPlaceholder, text: $vm.input, axis: .vertical)
                    .textFieldStyle(.plain)
                    .font(.system(size: 16))
                    .padding(.horizontal, 24)
                    .padding(.vertical, 24)
                    .frame(minHeight: 120, alignment: .topLeading)
                    .background(RoundedRectangle(cornerRadius: 28).fill(AppColors.inputFill))
                    .overlay(RoundedRectangle(cornerRadius: 28).stroke(AppColors.inputBorder.opacity(0.3), lineWidth: 1.5))
                    .lineLimit(1...12)
                    .disabled(!vm.isReady)

                Button(AppConfig.sendButtonLabel) { vm.send() }
                    .buttonStyle(.borderedProminent)
                    .tint(AppColors.accent)
                    .clipShape(RoundedRectangle(cornerRadius: 30))
                    .padding(.top, 20)
                    .disabled(vm.input.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || !vm.isReady)
            }
            .padding(.horizontal, 24)
            .padding(.vertical, 24)
        }
#if os(macOS)
        .background(Color(NSColor.controlBackgroundColor))
#else
        .background(Color(.systemBackground))
#endif
        .clipShape(RoundedRectangle(cornerRadius: 16))
        .padding(.horizontal, 8)
    }

    private var modelLoadingOverlay: some View {
        Group {
            if vm.isModelLoading {
                ZStack {
                    Color.black.opacity(0.6).ignoresSafeArea()
                    VStack(spacing: 20) {
                        Image("Logo").resizable().aspectRatio(contentMode: .fit)
                            .frame(width: 80, height: 80).shadow(radius: 10)
                        if let progress = vm.modelLoadProgress {
                            VStack(spacing: 12) {
                                Text(AppConfig.loadingTitle).font(.title3.bold())
                                ProgressView(value: progress.fractionCompleted) {
                                    Text("\(Int(progress.fractionCompleted * 100))%")
                                        .font(.caption).foregroundColor(.secondary)
                                }
                                .progressViewStyle(.linear)
                                .frame(width: 200)
                                .tint(AppColors.accent)
                            }
                        } else {
                            VStack(spacing: 12) {
                                Text(AppConfig.loadingTitle).font(.title3.bold())
                                ProgressView().progressViewStyle(.circular).scaleEffect(1.2)
                            }
                        }
                        Text(AppConfig.loadingSubtitle).font(.subheadline).foregroundColor(.secondary)
                    }
                    .padding(40)
                    .background(RoundedRectangle(cornerRadius: 20).fill(.regularMaterial)
                        .shadow(color: .black.opacity(0.3), radius: 20))
                }
                .transition(.opacity)
                .animation(.easeInOut, value: vm.isModelLoading)
            }
        }
    }
}

#Preview { ContentView() }
